### ISSUE TITLE
Example config yml has bad indentation

### ISSUE THREAD

**Issue by yamikuronue** [yamikuronue/sockMafia#28]
Adjusting the values in the example config.yml without touching the indentation does not parse, as it has bad indentation.

**Comment by AccaliaDeElementia** [comment]
actually it's a missing colon....

this works: although the plugin path is invalid in the current version of sockbot. I've got to solve that one. :-/

```
---
core:
  username: username
  password: password
  owner: accalia
  ignoreUsers:
    - blakeyrat
    - PaulaBean
  ignoreCategories:
    - 8
    - 23
  cooldownPeriod: 0
plugins:
  './plugins/mafiabot':
    thread: 52778
    mods:
     - mod
    players:
     - player1
     - player2
    db: './mafiadb'
    name: testMafia
```
